f1 = 'sqsetiitpgtipbsidhiaptisadpcdbialkvpaetiigsetiuletisptjudtetisadpkitdslmpjneixplvtdltgacictsptcihckabsefanciecntiqsllcttcnfejdplnwbpitiiedjblhpiatehoaesixjvsclsqsgodhiaiivdxiickivniekcdcadebsiggcipqsecntiodhiabpitisadpjslbalclxpjslitulalaqeteodhiaijschtisadpstsitiibpalbkelkpelobtocsaiodhiaucasdletisadpacobjinpgtlbaiappjslfsodhiajiitisadpcexjbthpspjidillpjhsaoacetmptilitesoslkbtbactipxeshcdubsaddteebaidpabqilitctcmuncuigtlsoscdeitcbfafseodhiaaspviapbotiehqsktslmpcmdjilbtmtiliterixpfibsbqilituqsibacqlpehqsktieoatekxaiuqsiodhiaebspivuapshlitienfpsqxslmpluncqilttilbehitvopbtifliaeqaseikpiaesjtsoblfsapidujudsshklitltephqsktapblilesealulpatcabstqeeibqesaealpipuiuctgahspjsllitoaeubscdpitstiwnavskteblsaitvfllkcdlhvsigtefncqilttctiealulpcdakicatgldnpetisipeslqiemuliaicdidsclicivsdolfjsadpablhiatietenvpcclibpuhutxaiqxshuilfudijelbsadpfeeitcgccdfudiixiutptgaiteinaqeteetldnhtotilbudjesictcloiqxuqslijeslbapxucgteapbactspltiiaptlkhpejhplitcptstiastcxusqlfcxuseitillnuixeeslmptetleqsulxealtisadpjnbbdkekcqjbviajlvtskvpbtiiodpuibtiticqlpenbvaqetbqilitqpdbtpopplqatefudeiepfbtektebanhecipodhiaembngsxjpsdhptieagntilbspltieilvplpeoggcipkpsnektielptiixsapifselodcioetebqilitbailitpiitcptdxslmpfliebpavncccudsreciiakitdxlbsctlfakidbtbsfaubelhaegtchuthqsktptnkcbhuvlnpitatbaeptcodhiasqsiddpoaqellkeiplltiieipetpttctisqaniiscbdsllpbjnelkctisoopainsdsxilignilklfstghontbfvsiitidxntsbqilitclqcbdxbbuijisapclicdntnehnceclpcnaltisplqicclpjsltlniqttiixitjetetiiiccdljlpabqcfaiedihieibnatiilitijajvdplqschcdlnnetieipiteeleagiavclceaheabiqsfesomplhiapuijbtnkcbescliptclciklatisfflibtciastitgntfdasledseetpibfsetisptjudteffnphaclxideeletiaetldvhtiastcldiptideqsalpjbafaitasicgk'
f2 = 'betvspbdublbihmwdjvhoskbdbtvtbvgvbbtansppbwasinhastddxevhdvskbdbtnbbpoibwgwpmhovdbspebbtoabdddmrsvbtbephibnoamesnhtikvwemeivdbthbihuwsninetbnefnhdvebigtwehbctpbetxndjvnidbcuvnmnvdmoobvkwbtihmwhcudhbwvmbtnndjvthjoskbdbteswektmthoeswvswhtigknanndjvknepvbskbdbtbgvoswthjlthmlvbipgthbcnhwondjvctwgbspaskbdbtlnteabduesvdknehoeswejndjveanoskbdbtiketbdjehodmwoteehsdthinmhdusmcnxabhjvthtdlwseminbtvhtedbbddvadnhdutbnwovlwsvamxpwoxswbhjvvtostbhhhbandjvwteudletbhtnaexdspoibwwbdsputhbsmcnxagndustbtbnwovwketodiphuanexdsnanhwnvmhswketondjvwtbbohenhobbfosamedubmpoibwamxknihbsnutanhdbblbsnntnipebwnvdbntkedaetbnejdobenevbwbevwoswehoexdsdbwnvovgivtttehdwxtbbenpttbnubwaibihowamnwxbgduemptodbthtewvdfvewsbigdbdsttbnbkidbntvwvowebdwgxgdmknihbstsivtttelwbdvomeegmhhoasabhogwpmamcwvwpvvnhbwmjtjhbxdfbekbdbtlevnhbsiwwadduttplbenevndobmahtnotemchemwkbdbtskjostbnvdemcfnnmihtebbvekvxgknxgvswbdhbhtnwemeigwwxsthobmwketfexgnuthoenpddvdtdptbhoasndhxsvdhoeheaovdmhgbevgbstehbhostehblosvlmwnmowpoibwejswketvtthjaskbdbtbtbhheonwetbdleswebwdbthswbbgwnlbsnsiphulgohbgkntbnwovedbthhxhdsweddvemmftjetbsgswadbbtnthondjvtetbdbtedtegduskwddddwvbbtvsvfmvbtewanhcuhobbhoobsvtewsnckbbtobbapbdtdknttbnwovlebfovdtnwlwebcpoibwsmvtduegunwqdkeglwfvguwbcbtbknxthhnbthtbbhpitowgwvesievwexdshobbnkdwnbmhiddhtdkdtstndjvwbetvbehetnpwvvthotwsnanganghbstskeehvfnbibagtetbemlvoxskdbddtneobcntnobdfvswejebekbbebbwfvbvhwhbtbnwovlwpbibctbewenkbbttfwvhmhjaemcntelwetvsahtinknteweswnhowdbsfncwbanwasuvnmvswnbotbmvhcxvnwgvvtbbwsofidwmdebdbtpetvbvlmhmlsufnpvtpvtngfndbuttnhnwtbpdbshbhduvnhduwetbbbnkteuvwhoeutthhvtsievsmthpxvgbswhddxbbdbvnbtivdgtbejastddxevhdvbdmbbwnmvbtpvtnsgbaswbdbevgbsttewemhtekbweetebbbjebfcchb'




ptext = ''

i = 0
while True:
    a=False
    b=False
    try:
        ptext+=f1[i]
    except:
        a=True
    try:
        ptext+=f2[i]
    except:
        b=True
    i+=1
    if a and b:
        break
print(ptext)